export const programsArray: string[] = [
    "Accounting",
    "Actuarial Science",
    "African Studies",
    "Aging and Society",
    "American Studies",
    "Animal Physiology",
    "Anthropology (Arts)",
    "Anthropology (Science)",
    "Anthropology: Evolutionary",
    "Anthropology: General (Arts)",
    "Anthropology: Society, Culture and Language",
    "Anthropology: Socio-Cultural",
    "Applied Climatology",
    "Applied Data Science",
    "Applied Mathematics",
    "Applied Statistics",
    "Archaeology",
    "Architectural Studies",
    "Art History",
    "Art History and Visual Culture",
    "Art and Art History",
    "Artist Diploma (Music)",
    "Arts Management",
    "Arts and Media Management",
    "Asian Canadian Studies",
    "Astronomical Sciences",
    "Astronomy",
    "Astronomy and Astrophysics",
    "Astronomy and Physics",
    "Biochemistry",
    "Biodiversity and Conservation Biology",
    "Bioethics",
    "Bioinformatics and Computational Biology",
    "Biological Chemistry",
    "Biological Physics",
    "Biology",
    "Biology for Health Sciences",
    "Biomedical Communications",
    "Biomedical Ethics",
    "Biomedical Toxicology",
    "Biophysics",
    "Biotechnology",
    "Book and Media Studies",
    "Buddhist Studies",
    "Business German",
    "Business, Science and Entrepreneurship",
    "Canadian Studies",
    "Caribbean Studies",
    "Cell and Molecular Biology",
    "Celtic Studies",
    "Chemical Engineering",
    "Chemical Physics",
    "Chemistry",
    "Chinese Language and Culture",
    "Christianity and Culture",
    "Christianity and Education",
    "Cinema Studies",
    "City Studies",
    "Civil Engineering",
    "Classical Civilization",
    "Classical Studies",
    "Classics (Greek and Latin)",
    "Cognitive Science (Arts)",
    "Cognitive Science (Science)",
    "Commerce",
    "Commerce (Arts)",
    "Communication, Culture, Information and Technology",
    "Comparative Physiology",
    "Composition (Music)",
    "Computer Engineering",
    "Computer Science",
    "Computer Science: Comprehensive Stream",
    "Computer Science: Entrepreneurship Stream",
    "Computer Science: Information Systems Stream",
    "Computer Science: Software Engineering Stream",
    "Conservation and Biodiversity",
    "Contemporary Asian Studies, Dr. David Chu Program in",
    "Creative Writing",
    "Creativity and Society",
    "Criminology and Sociolegal Studies",
    "Criminology, Law and Society",
    "Critical Migration Studies",
    "Critical Studies in Equity and Solidarity",
    "Culture, Creativity and Cities",
    "Data Science",
    "Diaspora and Transnational Studies",
    "Digital Enterprise Management",
    "Digital Humanities",
    "Drama",
    "Dramaturgy and Drama Studies",
    "Earth Science",
    "Earth and Environmental Systems",
    "East Asian Studies",
    "Ecology and Evolution",
    "Ecology and Evolutionary Biology",
    "Economics (Arts)",
    "Economics (Commerce)",
    "Economics and Mathematics",
    "Economics and Political Science",
    "Economics for Management Studies (Arts)",
    "Economics for Management Studies (Business)",
    "Education Studies",
    "Education and Society",
    "Electrical Engineering",
    "Engineering Science",
    "English",
    "English Language Linguistics",
    "English and Chinese Translation",
    "Environment and Behaviour",
    "Environment and Energy",
    "Environment and Health",
    "Environment and Toxicology",
    "Environmental Anthropology",
    "Environmental Biology",
    "Environmental Chemistry",
    "Environmental Economics",
    "Environmental Ethics",
    "Environmental Geography",
    "Environmental Geoscience",
    "Environmental Geosciences",
    "Environmental Law and Policy",
    "Environmental Management",
    "Environmental Physics",
    "Environmental Science",
    "Environmental Studies",
    "Ethics, Law and Society",
    "Ethics, Society and Law",
    "European Affairs",
    "Exceptionality in Human Learning",
    "Film Studies",
    "Finance",
    "Finance and Economics",
    "Financial Economics",
    "Food Studies",
    "Forensic Anthropology",
    "Forensic Biology",
    "Forensic Chemistry",
    "Forensic Psychology",
    "Forensic Science",
    "Forest Conservation",
    "Forest Conservation Science",
    "French",
    "French Language",
    "French Language Learning",
    "French Language and French Linguistics",
    "French Language and Literature",
    "French Studies",
    "Functional French",
    "Game Studies",
    "Genome Biology",
    "GeoSpatial Data Science",
    "Geographic Information Science",
    "Geography (Arts)",
    "Geography (Science)",
    "Geography: Human",
    "Geography: Physical and Human",
    "Geology",
    "Geophysics",
    "Geoscience",
    "German Studies",
    "German Studies in English",
    "Global Asia Studies",
    "Global Environmental Change",
    "Global Leadership",
    "Greek",
    "Health Humanities",
    "Health Policy",
    "History",
    "History and Philosophy of Science and Technology",
    "History and Political Science",
    "History of Religions",
    "History, Culture and Theory (Music)",
    "Human Biology",
    "Human Biology: Fundamental Genetics and its Applications",
    "Human Biology: Global Health",
    "Human Biology: Health and Disease",
    "Human Biology: Neuroscience",
    "Human Geography",
    "Human Resource Management",
    "Immunology",
    "Indigenous Studies",
    "Industrial Engineering",
    "Industrial Relations and Human Resources",
    "Information",
    "Information Security",
    "Integrative Biology",
    "Interdisciplinary Music Studies: Classical or Jazz",
    "International Affairs",
    "International Development Studies (Arts)",
    "International Development Studies (Science)",
    "International Relations",
    "Islamic Studies",
    "Italian",
    "Italian Culture and Communication Studies",
    "Italian Language and Culture",
    "Jewish Studies",
    "Journalism",
    "Kinesiology and Physical Education",
    "Language Teaching and Learning: French",
    "Language Teaching and Learning: French and Italian",
    "Language Teaching and Learning: Italian",
    "Latin",
    "Latin American Studies",
    "Latin American and Caribbean Studies",
    "Linguistic Studies",
    "Linguistics",
    "Literature and Critical Theory",
    "Management (Arts)",
    "Management (Business)",
    "Management (Commerce)",
    "Management and Accounting",
    "Management and Finance",
    "Management and Finance + Statistics: Quantitative Finance Stream",
    "Management and Human Resources",
    "Management and Information Technology",
    "Management and International Business",
    "Management and Marketing",
    "Marketing",
    "Material Culture and Semiotics",
    "Materials Engineering",
    "Materials Science",
    "Mathematical Applications in Economics and Finance",
    "Mathematical Sciences",
    "Mathematics",
    "Mathematics and Philosophy",
    "Mathematics and Physics",
    "Mathematics and its Applications: Physical Science",
    "Mathematics and its Applications: Probability/Statistics",
    "Mathematics and its Applications: Teaching",
    "Mathematics: Comprehensive Stream",
    "Mathematics: Statistics Stream",
    "Mathematics: Teaching Stream",
    "Mechanical Engineering",
    "Media Studies",
    "Media and Communication Studies: Journalism Studies Stream",
    "Media and Communication Studies: Media Studies Stream",
    "Mediaeval Studies",
    "Medical Anthropology",
    "Medical Radiation Sciences",
    "Medicinal and Biological Chemistry",
    "Mental Health Studies",
    "Mineral Engineering",
    "Molecular Biology",
    "Molecular Biology and Biotechnology",
    "Molecular Biology, Immunology and Disease",
    "Molecular Genetics and Microbiology",
    "Music",
    "Music Education: Classical or Jazz",
    "Music History and Culture",
    "Music Industry and Technology",
    "Music with Ensemble Option",
    "Natural Sciences and Environmental Management",
    "Near and Middle Eastern Civilizations",
    "Neuroscience",
    "Nursing",
    "Nutritional Sciences",
    "Paleontology",
    "Paramedicine",
    "Pathobiology",
    "Peace, Conflict and Justice",
    "Performance: Classical or Jazz",
    "Pharmaceutical Chemistry",
    "Pharmacology",
    "Pharmacology and Biomedical Toxicology",
    "Philosophy",
    "Philosophy of Science",
    "Physical Sciences",
    "Physical and Environmental Geography",
    "Physical and Mathematical Sciences",
    "Physician Assistant",
    "Physics",
    "Physics and Astrophysics",
    "Physics and Philosophy",
    "Physiology",
    "Planetary Science",
    "Plant Biology",
    "Political Science",
    "Population Health",
    "Portuguese",
    "Professional Writing and Communication",
    "Psycholinguistics",
    "Psychology",
    "Psychology Research",
    "Public Health",
    "Public Law",
    "Public Policy",
    "Quantitative Biology",
    "Religion",
    "Renaissance Studies",
    "Science, Technology and Society",
    "Sexual Diversity Studies",
    "Slavic and East European Languages and Cultures",
    "Slavic and East European Literature in Translation",
    "Sociology",
    "South Asian Humanities",
    "South Asian Studies",
    "Spanish",
    "Statistical Science: Methods and Practice",
    "Statistical Science: Theory and Methods",
    "Statistics",
    "Statistics: Quantitative Finance Stream",
    "Statistics: Statistical Machine Learning and Data Science Stream",
    "Statistics: Statistical Sciences Stream",
    "Strategic Management",
    "Studio Art",
    "Sustainability",
    "Synthetic and Catalytic Chemistry",
    "Technology, Coding and Society",
    "Theatre and Drama Studies",
    "Theatre and Performance",
    "Track One: Undeclared Engineering",
    "Urban Public Policy and Governance",
    "Urban Studies",
    "Visual Culture",
    "Visual Culture and Communication",
    "Visual Studies (Arts)",
    "Visual Studies (Design)",
    "Women and Gender Studies",
    "Women&#039;s and Gender Studies",
    "Women, Gender and Sexuality Studies",
    "Work and Organizations: Humanities Contexts",
    "Work and Organizations: Sciences Contexts",
    "Work and Organizations: Social Sciences Contexts",
    "Writing and Rhetoric",
    "Yiddish, Al and Malka Green Program in",
];

export const programs = programsArray.map((program) => {
    return {
        value: program,
        label: program,
    };
});
