export const TAGS: string[] = [
    "JavaScript",
    "HTML",
    "CSS",
    "NodeJS",
    "Python",
    "Java",
    "React",
    "GitHub",
    "Visual Studio Code",
    "npm",
    "Git",
    "Google Chrome",
    "Windows",
    "Linux",
    "Android",
    "iOS",
    "macOS",
    "AWS",
    "Google",
    "YouTube",
    "Facebook",
    "TypeScript",
    "C++",
    "C#",
    "PHP",
    "Go",
    "Ruby",
    "Swift",
    "Kotlin",
    "Rust",
    "Microsoft Azure",
    "Google Cloud",
    "Docker",
    "WordPress",
    "MySQL",
    "Postgres",
    "MongoDB",
    "SQLite",
    "Redis",
    "Next.js",
    "Angular",
    "Vue.js",
    "jQuery",
    "Bootstrap",
    "TailwindCSS",
    ".NET",
    "Spring Boot",
    "Django",
    "Laravel",
    "Rails",
    "Express.js",
    "Flask",
    "React Native",
    "Flutter",
    "Electron",
    "Vite",
    "Redux",
    "Svelte",
    "Webpack",
    "Babel",
    "Jest",
    "GitLab",
    "Jira",
    "Confluence",
    "Slack",
    "IntelliJ IDEA",
    "PyCharm",
    "WebStorm",
    "Visual Studio",
    "Sublime Text",
    "Vim",
    "Neovim",
    "Stack Overflow",
    "Microsoft SQL Server",
    "Oracle",
    "Firebase",
    "Kubernetes",
    "Jenkins",
    "GitHub Actions",
    "GitLab CI",
    "CircleCI",
    "Travis CI",
    "Terraform",
    "Ansible",
    "Prometheus",
    "Grafana",
    "Elasticsearch",
    "Snowflake",
    "Datadog",
    "Splunk",
    "New Relic",
    "Sass",
    "Less",
    "Stylus",
    "PostCSS",
    "GraphQL",
    "Apollo",
    "REST",
    "gRPC",
    "WebSockets",
    "WebAssembly",
    "PWA",
    "AMP",
    "JAMstack",
    "Serverless",
    "Microservices",
    "Blockchain",
    "Web3",
    "AR",
    "VR",
    "AI",
    "Machine Learning",
    "Data Science",
    "Big Data",
    "IoT",
    "Gaming",
    "E-commerce",
    "FinTech",
    "HealthTech",
    "EdTech",
    "Crystal",
    "Eleventy",
    "Crunchyroll",
    "Khan Academy",
    "AniList",
    "Scala",
    "Threads",
    "TuneIn",
    "DuckDuckGo",
    "NuGet",
    "Bitbucket",
    "WhatsApp",
    "Amazon Prime",
    "GrubHub",
    "Humble Bundle",
    "Mega",
    "GNU",
    "Bun",
    "Blazor",
    "YAML",
    "Pandas",
    "Symfony",
    "Wezterm",
    "Dribble",
    "Perplexity",
    "Matrix",
    "Tableau",
    "Vuetify",
    "Subversion",
    "PayPal",
    "WooCommerce",
    "Xcode",
    "Zoom",
    "InfluxDB",
    "Expo",
    "Replit",
    "Nuxt",
    "DigitalOcean",
    "Alipay",
    "Epic Games",
    "Dart",
    "Solana",
    "Deepseek",
    "Dogecoin",
    "Pinterest",
    "Signal",
    "Neo4J",
    "Squarespace",
    "Firebase Studio",
    "Google Gemini",
    "Bitcoin SV",
    "Bilibili",
    "MyAnimeList",
    "Ember.js",
    "Tubi",
    "NetBeans IDE",
    "Tauri",
    "Stripe",
    "Trello",
    "Viber",
    "Sequelize",
    "Github Sponsors",
    "Uber Eats",
    "Udemy",
    "Solidity",
    "Contentful",
    "Odoo",
    "Product Hunt",
    "Semaphore",
    "Polkadot",
    "Uplay",
    "React Table",
    "G2",
    "LastFM",
    "Session",
    "Spotify",
    "Flathub",
    "edX",
    "Strapi",
    "G2A",
    "Google Play Store",
    "Mastodon",
    "LINE",
    "CouchDB",
    "RenovateBot",
    "Audacity",
    "Safari",
    "Unsplash",
    "Medium",
    "Reddit",
    "Apple Podcasts",
    "Discord",
    "EJS",
    "GitBook",
    "Baidu",
    "Stellar",
    "Nim",
    "MkDocs",
    "Ren'Py",
    "PyPI",
    "YouTube Music",
    "GitHub Copilot",
    "Bamboo",
    "Flickr",
    "Liberapay",
    "Hexo",
    "ArangoDB",
    "Arc",
    "Elm",
    "NixOS",
    "Claude",
    "Roku",
    "Heroku",
    "Ubuntu",
    "Perforce",
    "HTMX",
    "Upwork",
    "Obsidian",
    "Storybook",
    "Kali Linux",
    "Codeberg",
    "GOG.com",
    "Preact",
    "Python IDLE",
    "Google Cardboard",
    "Monero",
    "Power BI",
    "X",
    "Alibaba Cloud",
    "Deliveroo",
    "Coveralls",
    "Max",
    "Octopus Deploy",
    "Krita",
    "Just Eat",
    "SteamVR",
    "Wix",
    "Opera GX",
    "Erlang",
    "Wagmi",
    "CoffeeScript",
    "TikTok",
    "PlayStation VR",
    "Linux Mint",
    "tmux",
    "VSCodium",
    "MDN Web Docs",
    "Tidal",
    "Hashnode",
    "Gimp",
    "Glassdoor",
    "ARKit",
    "Snyk",
    "CodePen",
    "Twitch",
    "Bash",
    "Code Climate",
    "Instagram",
    "Jasmine",
    "Codecademy",
    "Notepad++",
    "Steam",
    "Goodreads",
    "Apple Music",
    "iCloud",
    "Codewars",
    "Ripple",
    "TensorFlow",
    "Bluesky",
    "MasterCard",
    "Square",
    "Cloudflare",
    "Helm",
    "TypeORM",
    "Hugging Face",
    "React Hook Form",
    "SketchUp",
    "Bitcoin Cash",
    "Markdown",
    "Zed",
    "Apple TV",
    "AOL",
    "Chocolatey",
    "Deno",
    "Netlify",
    "React Query",
    "App Store",
    "Jekyll",
    "Coursera",
    "Matplotlib",
    "Construct 3",
    "Warp",
    "Substack",
    "StackHawk",
    "Gentoo",
    "Yelp",
    "Chart.js",
    "Drizzle",
    "TeamSpeak",
    "Lua",
    "Manjaro",
    "Scratch",
    "Pandora",
    "Unity",
    "Box",
    "Vercel",
    "C",
    "DynamoDB",
    "Chainlink",
    "Cypress",
    "Website",
    "The Odin Project",
    "Bitcoin",
    "Unreal Engine",
    "Pixiv",
    "Cassandra",
    "Open Collective",
    "VuePress",
    "Odin",
    "CryEngine",
    "Helix",
    "Codecov",
    "Telegram",
    "Fiverr",
    "Alacritty",
    "Backbone.js",
    "Zcash",
    "Amazon Alexa",
    "Selenium",
    "Supabase",
    "Perl",
    "Viem",
    "KDE Plasma",
    "XRP",
    "Oracle Cloud",
    "Visa",
    "ReadMe",
    "Gridsome",
    "Google Assistant",
    "OCaml",
    "Vitest",
    "Apple Pay",
    "Couchbase",
    "Snapcraft",
    "Bitbucket Pipelines",
    "Fortran",
    "Docusaurus",
    "Fastify",
    "Inkscape",
    "Docsify",
    "Stack Exchange",
    "Framer",
    "FreeBSD",
    "Miro",
    "Pluralsight",
    "Nintendo eShop",
    "pnpm",
    "Blogger",
    "Guilded",
    "Amazon Lumberyard",
    "Proton Mail",
    "Amazon Pay",
    "Nest",
    "Ethereum",
    "Elixir",
    "MDX",
    "AppVeyor",
    "React Router",
    "Gatsby",
    "Zsh",
    "Astro",
    "GNOME Terminal",
    "Skillshare",
    "Fedora",
    "Hyper",
    "LinkedIn",
    "GameMaker",
    "Cardano",
    "Netflix",
    "Alura",
    "iTerm2",
    "Vivaldi",
    "V",
    "SonarCloud",
    "v0",
    "GeeksForGeeks",
    "Read the Docs",
    "Indeed",
    "Ko-Fi",
    "Haxe",
    "American Express",
    "Prisma",
    "Tor",
    "MariaDB",
    "Payoneer",
    "AlmaLinux",
    "GitHub Pages",
    "Pop!_OS",
    "WeChat",
    "Behance",
    "Alpine Linux",
    "Dependabot",
    "Eclipse",
    "Void Linux",
    "Battle.net",
    "Asana",
    "Hostinger",
    "Linktree",
    "Pelican",
    "JSR",
    "MX Linux",
    "Solid",
    "Haskell",
    "Firefox",
    "R",
    "LeetCode",
    "Dropbox",
    "Hibernate",
    "Blender",
    "Klarna",
    "NumPy",
    "Foundry",
    "Origin",
    "Mocha",
    "Asahi Linux",
    "Soundcloud",
    "Notion",
    "Google Pay",
    "Linear",
    "Homebrew",
    "CodeSandbox",
    "Meteor.js",
    "Gitpod",
    "Hono",
    "Godot Engine",
    "Shazam",
    "Canva",
    "Anaconda",
    "Litecoin",
    "Codemagic",
    "Patreon",
    "PyTorch",
    "Figma",
    "Kick",
    "shadcn/ui",
    "Treehouse",
    "Itch.io",
    "Objective-C",
    "freeCodeCamp",
    "Tether",
    "Arch Linux",
    "Messenger",
    "Alpine.js",
    "DaisyUI",
    "Oculus",
    "Rider",
    "Hugo",
    "Scikit-learn",
    "Mercurial",
    "Dev.to",
    "ETL",
    "Gmail",
    "Nix",
    "Proton Drive",
    "Zig",
    "Remix",
    "FastAPI",
    "Artix Linux",
    "SAP",
    "styled-components",
    "Opera",
    "BeReal",
    "Composer",
    "Rocky Linux",
    "Gitea",
    "Yarn",
    "LinkedIn Learning",
    "Monster",
    "Ghost",
    "Udacity",
    "Playwright",
    "PhpStorm",
    "Doordash",
    "W3Schools",
    "XML",
    "Emacs",
    "SvelteKit",
    "Three.js",
    "DeviantArt",
    "Sphinx",
    "Teradata",
    "Codacy",
    "Buy Me A Coffee",
    "F#",
    "Quora",
    "Brave",
    "JSON",
    "Google Drive",
    "EA",
    "AssemblyScript",
    "Clojure",
    "Snapchat",
    "ChatGPT",
    "Debian",
    "Shopify",
    "Google Colab",
    "Trustpilot",
    "PlayStation Store",
    "Tumblr",
];
