export const TAGS: { id: string; label: string }[] = [
    { id: "Crystal", label: "Crystal" },
    { id: "Eleventy", label: "Eleventy" },
    { id: "Crunchyroll", label: "Crunchyroll" },
    { id: "Khan Academy", label: "Khan Academy" },
    { id: "AniList", label: "AniList" },
    { id: "Scala", label: "Scala" },
    { id: "Threads", label: "Threads" },
    { id: "TuneIn", label: "TuneIn" },
    { id: "DuckDuckGo", label: "DuckDuckGo" },
    { id: "NuGet", label: "NuGet" },
    { id: "Bitbucket", label: "Bitbucket" },
    { id: "WhatsApp", label: "WhatsApp" },
    { id: "Amazon Prime", label: "Amazon Prime" },
    { id: "GrubHub", label: "GrubHub" },
    { id: "Humble Bundle", label: "Humble Bundle" },
    { id: "Mega", label: "Mega" },
    { id: "GNU", label: "GNU" },
    { id: "Bun", label: "Bun" },
    { id: "Blazor", label: "Blazor" },
    { id: "YAML", label: "YAML" },
    { id: "Pandas", label: "Pandas" },
    { id: "Symfony", label: "Symfony" },
    { id: "Wezterm", label: "Wezterm" },
    { id: "Dribble", label: "Dribble" },
    { id: "Perplexity", label: "Perplexity" },
    { id: "Matrix", label: "Matrix" },
    { id: "Tableau", label: "Tableau" },
    { id: "Vuetify", label: "Vuetify" },
    { id: "Subversion", label: "Subversion" },
    { id: "PayPal", label: "PayPal" },
    { id: "WooCommerce", label: "WooCommerce" },
    { id: "Xcode", label: "Xcode" },
    { id: "Zoom", label: "Zoom" },
    { id: "InfluxDB", label: "InfluxDB" },
    { id: "Expo", label: "Expo" },
    { id: "Replit", label: "Replit" },
    { id: "Nuxt", label: "Nuxt" },
    { id: "DigitalOcean", label: "DigitalOcean" },
    { id: "GitLab", label: "GitLab" },
    { id: "Docker", label: "Docker" },
    { id: "Alipay", label: "Alipay" },
    { id: "Epic Games", label: "Epic Games" },
    { id: "Dart", label: "Dart" },
    { id: "Solana", label: "Solana" },
    { id: "Deepseek", label: "Deepseek" },
    { id: "Dogecoin", label: "Dogecoin" },
    { id: "Ruby", label: "Ruby" },
    { id: "Pinterest", label: "Pinterest" },
    { id: "Signal", label: "Signal" },
    { id: "Jenkins", label: "Jenkins" },
    { id: "Flask", label: "Flask" },
    { id: "Neo4J", label: "Neo4J" },
    { id: "GitHub Actions", label: "GitHub Actions" },
    { id: "Squarespace", label: "Squarespace" },
    { id: "Firebase Studio", label: "Firebase Studio" },
    { id: "Google Gemini", label: "Google Gemini" },
    { id: "Redux", label: "Redux" },
    { id: "Bitcoin SV", label: "Bitcoin SV" },
    { id: "Bilibili", label: "Bilibili" },
    { id: "MyAnimeList", label: "MyAnimeList" },
    { id: "Ember.js", label: "Ember.js" },
    { id: "Tubi", label: "Tubi" },
    { id: "Visual Studio Code", label: "Visual Studio Code" },
    { id: "NetBeans IDE", label: "NetBeans IDE" },
    { id: "Tauri", label: "Tauri" },
    { id: "Stripe", label: "Stripe" },
    { id: "Trello", label: "Trello" },
    { id: "Viber", label: "Viber" },
    { id: "Sequelize", label: "Sequelize" },
    { id: "Github Sponsors", label: "Github Sponsors" },
    { id: "Uber Eats", label: "Uber Eats" },
    { id: "Udemy", label: "Udemy" },
    { id: "Solidity", label: "Solidity" },
    { id: "React Native", label: "React Native" },
    { id: "Contentful", label: "Contentful" },
    { id: "Odoo", label: "Odoo" },
    { id: "Product Hunt", label: "Product Hunt" },
    { id: "Semaphore", label: "Semaphore" },
    { id: "Polkadot", label: "Polkadot" },
    { id: "Uplay", label: "Uplay" },
    { id: "React Table", label: "React Table" },
    { id: "macOS", label: "macOS" },
    { id: "G2", label: "G2" },
    { id: "LastFM", label: "LastFM" },
    { id: "Session", label: "Session" },
    { id: "Spotify", label: "Spotify" },
    { id: "Flathub", label: "Flathub" },
    { id: "edX", label: "edX" },
    { id: "Strapi", label: "Strapi" },
    { id: "G2A", label: "G2A" },
    { id: "Google Play Store", label: "Google Play Store" },
    { id: "Mastodon", label: "Mastodon" },
    { id: "iOS", label: "iOS" },
    { id: "LINE", label: "LINE" },
    { id: "TailwindCSS", label: "TailwindCSS" },
    { id: "CouchDB", label: "CouchDB" },
    { id: "RenovateBot", label: "RenovateBot" },
    { id: "Audacity", label: "Audacity" },
    { id: "Safari", label: "Safari" },
    { id: "Unsplash", label: "Unsplash" },
    { id: "Rust", label: "Rust" },
    { id: "Medium", label: "Medium" },
    { id: "Reddit", label: "Reddit" },
    { id: "Apple Podcasts", label: "Apple Podcasts" },
    { id: "Discord", label: "Discord" },
    { id: "EJS", label: "EJS" },
    { id: "GitBook", label: "GitBook" },
    { id: "Baidu", label: "Baidu" },
    { id: "Stellar", label: "Stellar" },
    { id: "Nim", label: "Nim" },
    { id: "MkDocs", label: "MkDocs" },
    { id: "Ren'Py", label: "Ren'Py" },
    { id: "AWS", label: "AWS" },
    { id: "PyPI", label: "PyPI" },
    { id: "YouTube Music", label: "YouTube Music" },
    { id: "Angular", label: "Angular" },
    { id: "GitHub Copilot", label: "GitHub Copilot" },
    { id: "Facebook", label: "Facebook" },
    { id: "Bamboo", label: "Bamboo" },
    { id: "Flickr", label: "Flickr" },
    { id: "Liberapay", label: "Liberapay" },
    { id: "Hexo", label: "Hexo" },
    { id: "ArangoDB", label: "ArangoDB" },
    { id: "Arc", label: "Arc" },
    { id: "Elm", label: "Elm" },
    { id: "NixOS", label: "NixOS" },
    { id: "Claude", label: "Claude" },
    { id: "Roku", label: "Roku" },
    { id: "Heroku", label: "Heroku" },
    { id: "Ubuntu", label: "Ubuntu" },
    { id: "Perforce", label: "Perforce" },
    { id: "HTMX", label: "HTMX" },
    { id: "React", label: "React" },
    { id: "Upwork", label: "Upwork" },
    { id: "Obsidian", label: "Obsidian" },
    { id: "Storybook", label: "Storybook" },
    { id: "Kali Linux", label: "Kali Linux" },
    { id: "Codeberg", label: "Codeberg" },
    { id: "GOG.com", label: "GOG.com" },
    { id: "Preact", label: "Preact" },
    { id: "Python IDLE", label: "Python IDLE" },
    { id: "Google Cardboard", label: "Google Cardboard" },
    { id: "Monero", label: "Monero" },
    { id: "Power BI", label: "Power BI" },
    { id: "X", label: "X" },
    { id: "Microsoft Azure", label: "Microsoft Azure" },
    { id: "Alibaba Cloud", label: "Alibaba Cloud" },
    { id: "Deliveroo", label: "Deliveroo" },
    { id: "Coveralls", label: "Coveralls" },
    { id: "Max", label: "Max" },
    { id: "Octopus Deploy", label: "Octopus Deploy" },
    { id: "Krita", label: "Krita" },
    { id: "Just Eat", label: "Just Eat" },
    { id: "SteamVR", label: "SteamVR" },
    { id: "Wix", label: "Wix" },
    { id: "Microsoft SQL Server", label: "Microsoft SQL Server" },
    { id: "Linux", label: "Linux" },
    { id: "Opera GX", label: "Opera GX" },
    { id: "Erlang", label: "Erlang" },
    { id: "Wagmi", label: "Wagmi" },
    { id: "CoffeeScript", label: "CoffeeScript" },
    { id: "TikTok", label: "TikTok" },
    { id: "PlayStation VR", label: "PlayStation VR" },
    { id: "Linux Mint", label: "Linux Mint" },
    { id: "tmux", label: "tmux" },
    { id: "VSCodium", label: "VSCodium" },
    { id: "MDN Web Docs", label: "MDN Web Docs" },
    { id: "Tidal", label: "Tidal" },
    { id: "Hashnode", label: "Hashnode" },
    { id: "Gimp", label: "Gimp" },
    { id: "CircleCI", label: "CircleCI" },
    { id: "Glassdoor", label: "Glassdoor" },
    { id: "ARKit", label: "ARKit" },
    { id: "Snyk", label: "Snyk" },
    { id: "CodePen", label: "CodePen" },
    { id: "Twitch", label: "Twitch" },
    { id: "Bash", label: "Bash" },
    { id: "Code Climate", label: "Code Climate" },
    { id: "Instagram", label: "Instagram" },
    { id: "Sublime Text", label: "Sublime Text" },
    { id: ".NET", label: ".NET" },
    { id: "Jasmine", label: "Jasmine" },
    { id: "Redis", label: "Redis" },
    { id: "Codecademy", label: "Codecademy" },
    { id: "Python", label: "Python" },
    { id: "Notepad++", label: "Notepad++" },
    { id: "Steam", label: "Steam" },
    { id: "Goodreads", label: "Goodreads" },
    { id: "Apple Music", label: "Apple Music" },
    { id: "iCloud", label: "iCloud" },
    { id: "Codewars", label: "Codewars" },
    { id: "Ripple", label: "Ripple" },
    { id: "PHP", label: "PHP" },
    { id: "TensorFlow", label: "TensorFlow" },
    { id: "Bluesky", label: "Bluesky" },
    { id: "MasterCard", label: "MasterCard" },
    { id: "Square", label: "Square" },
    { id: "Cloudflare", label: "Cloudflare" },
    { id: "Helm", label: "Helm" },
    { id: "TypeORM", label: "TypeORM" },
    { id: "Hugging Face", label: "Hugging Face" },
    { id: "Babel", label: "Babel" },
    { id: "Swift", label: "Swift" },
    { id: "React Hook Form", label: "React Hook Form" },
    { id: "Snowflake", label: "Snowflake" },
    { id: "SketchUp", label: "SketchUp" },
    { id: "Java", label: "Java" },
    { id: "Go", label: "Go" },
    { id: "Bitcoin Cash", label: "Bitcoin Cash" },
    { id: "JavaScript", label: "JavaScript" },
    { id: "Markdown", label: "Markdown" },
    { id: "Next.js", label: "Next.js" },
    { id: "Zed", label: "Zed" },
    { id: "Apple TV", label: "Apple TV" },
    { id: "AOL", label: "AOL" },
    { id: "Chocolatey", label: "Chocolatey" },
    { id: "Deno", label: "Deno" },
    { id: "Netlify", label: "Netlify" },
    { id: "React Query", label: "React Query" },
    { id: "App Store", label: "App Store" },
    { id: "Jekyll", label: "Jekyll" },
    { id: "Coursera", label: "Coursera" },
    { id: "Bootstrap", label: "Bootstrap" },
    { id: "npm", label: "npm" },
    { id: "Matplotlib", label: "Matplotlib" },
    { id: "Construct 3", label: "Construct 3" },
    { id: "Warp", label: "Warp" },
    { id: "Substack", label: "Substack" },
    { id: "StackHawk", label: "StackHawk" },
    { id: "Gentoo", label: "Gentoo" },
    { id: "Yelp", label: "Yelp" },
    { id: "Chart.js", label: "Chart.js" },
    { id: "Drizzle", label: "Drizzle" },
    { id: "TeamSpeak", label: "TeamSpeak" },
    { id: "Lua", label: "Lua" },
    { id: "Manjaro", label: "Manjaro" },
    { id: "Scratch", label: "Scratch" },
    { id: "Pandora", label: "Pandora" },
    { id: "Unity", label: "Unity" },
    { id: "Box", label: "Box" },
    { id: "Vercel", label: "Vercel" },
    { id: "C", label: "C" },
    { id: "DynamoDB", label: "DynamoDB" },
    { id: "Chainlink", label: "Chainlink" },
    { id: "IntelliJ IDEA", label: "IntelliJ IDEA" },
    { id: "Firebase", label: "Firebase" },
    { id: "Cypress", label: "Cypress" },
    { id: "Postgres", label: "Postgres" },
    { id: "Website", label: "Website" },
    { id: "The Odin Project", label: "The Odin Project" },
    { id: "Bitcoin", label: "Bitcoin" },
    { id: "Kubernetes", label: "Kubernetes" },
    { id: "Unreal Engine", label: "Unreal Engine" },
    { id: "Pixiv", label: "Pixiv" },
    { id: "Cassandra", label: "Cassandra" },
    { id: "Open Collective", label: "Open Collective" },
    { id: "VuePress", label: "VuePress" },
    { id: "Odin", label: "Odin" },
    { id: "CryEngine", label: "CryEngine" },
    { id: "Helix", label: "Helix" },
    { id: "Codecov", label: "Codecov" },
    { id: "Telegram", label: "Telegram" },
    { id: "Fiverr", label: "Fiverr" },
    { id: "Alacritty", label: "Alacritty" },
    { id: "Backbone.js", label: "Backbone.js" },
    { id: "Zcash", label: "Zcash" },
    { id: "TypeScript", label: "TypeScript" },
    { id: "Amazon Alexa", label: "Amazon Alexa" },
    { id: "Selenium", label: "Selenium" },
    { id: "Supabase", label: "Supabase" },
    { id: "Perl", label: "Perl" },
    { id: "Viem", label: "Viem" },
    { id: "KDE Plasma", label: "KDE Plasma" },
    { id: "XRP", label: "XRP" },
    { id: "Slack", label: "Slack" },
    { id: "Oracle Cloud", label: "Oracle Cloud" },
    { id: "Visa", label: "Visa" },
    { id: "ReadMe", label: "ReadMe" },
    { id: "Gridsome", label: "Gridsome" },
    { id: "Google Assistant", label: "Google Assistant" },
    { id: "OCaml", label: "OCaml" },
    { id: "Vitest", label: "Vitest" },
    { id: "Apple Pay", label: "Apple Pay" },
    { id: "C++", label: "C++" },
    { id: "Couchbase", label: "Couchbase" },
    { id: "Snapcraft", label: "Snapcraft" },
    { id: "Bitbucket Pipelines", label: "Bitbucket Pipelines" },
    { id: "Vim", label: "Vim" },
    { id: "Fortran", label: "Fortran" },
    { id: "Confluence", label: "Confluence" },
    { id: "Visual Studio", label: "Visual Studio" },
    { id: "Docusaurus", label: "Docusaurus" },
    { id: "Fastify", label: "Fastify" },
    { id: "Inkscape", label: "Inkscape" },
    { id: "Docsify", label: "Docsify" },
    { id: "Rails", label: "Rails" },
    { id: "Stack Exchange", label: "Stack Exchange" },
    { id: "AMP", label: "AMP" },
    { id: "Framer", label: "Framer" },
    { id: "FreeBSD", label: "FreeBSD" },
    { id: "Miro", label: "Miro" },
    { id: "Pluralsight", label: "Pluralsight" },
    { id: "Nintendo eShop", label: "Nintendo eShop" },
    { id: "pnpm", label: "pnpm" },
    { id: "Blogger", label: "Blogger" },
    { id: "Kotlin", label: "Kotlin" },
    { id: "Guilded", label: "Guilded" },
    { id: "Amazon Lumberyard", label: "Amazon Lumberyard" },
    { id: "Proton Mail", label: "Proton Mail" },
    { id: "Amazon Pay", label: "Amazon Pay" },
    { id: "Nest", label: "Nest" },
    { id: "Ethereum", label: "Ethereum" },
    { id: "Elixir", label: "Elixir" },
    { id: "MDX", label: "MDX" },
    { id: "AppVeyor", label: "AppVeyor" },
    { id: "React Router", label: "React Router" },
    { id: "Electron", label: "Electron" },
    { id: "Gatsby", label: "Gatsby" },
    { id: "Zsh", label: "Zsh" },
    { id: "Astro", label: "Astro" },
    { id: "GNOME Terminal", label: "GNOME Terminal" },
    { id: "Spring Boot", label: "Spring Boot" },
    { id: "WebStorm", label: "WebStorm" },
    { id: "Skillshare", label: "Skillshare" },
    { id: "Fedora", label: "Fedora" },
    { id: "Neovim", label: "Neovim" },
    { id: "Hyper", label: "Hyper" },
    { id: "LinkedIn", label: "LinkedIn" },
    { id: "GameMaker", label: "GameMaker" },
    { id: "Cardano", label: "Cardano" },
    { id: "Svelte", label: "Svelte" },
    { id: "Netflix", label: "Netflix" },
    { id: "Alura", label: "Alura" },
    { id: "iTerm2", label: "iTerm2" },
    { id: "Git", label: "Git" },
    { id: "Vivaldi", label: "Vivaldi" },
    { id: "V", label: "V" },
    { id: "SonarCloud", label: "SonarCloud" },
    { id: "v0", label: "v0" },
    { id: "GeeksForGeeks", label: "GeeksForGeeks" },
    { id: "Read the Docs", label: "Read the Docs" },
    { id: "Indeed", label: "Indeed" },
    { id: "Ko-Fi", label: "Ko-Fi" },
    { id: "Google Cloud", label: "Google Cloud" },
    { id: "Haxe", label: "Haxe" },
    { id: "American Express", label: "American Express" },
    { id: "Prisma", label: "Prisma" },
    { id: "Tor", label: "Tor" },
    { id: "MariaDB", label: "MariaDB" },
    { id: "Payoneer", label: "Payoneer" },
    { id: "Jira", label: "Jira" },
    { id: "AlmaLinux", label: "AlmaLinux" },
    { id: "GitHub Pages", label: "GitHub Pages" },
    { id: "PyCharm", label: "PyCharm" },
    { id: "Pop!_OS", label: "Pop!_OS" },
    { id: "WeChat", label: "WeChat" },
    { id: "Behance", label: "Behance" },
    { id: "Alpine Linux", label: "Alpine Linux" },
    { id: "Dependabot", label: "Dependabot" },
    { id: "Eclipse", label: "Eclipse" },
    { id: "Void Linux", label: "Void Linux" },
    { id: "Battle.net", label: "Battle.net" },
    { id: "Asana", label: "Asana" },
    { id: "Hostinger", label: "Hostinger" },
    { id: "Linktree", label: "Linktree" },
    { id: "Pelican", label: "Pelican" },
    { id: "JSR", label: "JSR" },
    { id: "MX Linux", label: "MX Linux" },
    { id: "Solid", label: "Solid" },
    { id: "Haskell", label: "Haskell" },
    { id: "Vite", label: "Vite" },
    { id: "Laravel", label: "Laravel" },
    { id: "Firefox", label: "Firefox" },
    { id: "R", label: "R" },
    { id: "LeetCode", label: "LeetCode" },
    { id: "Dropbox", label: "Dropbox" },
    { id: "Hibernate", label: "Hibernate" },
    { id: "Blender", label: "Blender" },
    { id: "Klarna", label: "Klarna" },
    { id: "NumPy", label: "NumPy" },
    { id: "Foundry", label: "Foundry" },
    { id: "Origin", label: "Origin" },
    { id: "Mocha", label: "Mocha" },
    { id: "Asahi Linux", label: "Asahi Linux" },
    { id: "Soundcloud", label: "Soundcloud" },
    { id: "Notion", label: "Notion" },
    { id: "Google Pay", label: "Google Pay" },
    { id: "Linear", label: "Linear" },
    { id: "Homebrew", label: "Homebrew" },
    { id: "CodeSandbox", label: "CodeSandbox" },
    { id: "Meteor.js", label: "Meteor.js" },
    { id: "Gitpod", label: "Gitpod" },
    { id: "Hono", label: "Hono" },
    { id: "Godot Engine", label: "Godot Engine" },
    { id: "Stack Overflow", label: "Stack Overflow" },
    { id: "Shazam", label: "Shazam" },
    { id: "Canva", label: "Canva" },
    { id: "Anaconda", label: "Anaconda" },
    { id: "Litecoin", label: "Litecoin" },
    { id: "Android", label: "Android" },
    { id: "Codemagic", label: "Codemagic" },
    { id: "Patreon", label: "Patreon" },
    { id: "PyTorch", label: "PyTorch" },
    { id: "Jest", label: "Jest" },
    { id: "Figma", label: "Figma" },
    { id: "Kick", label: "Kick" },
    { id: "C#", label: "C#" },
    { id: "shadcn/ui", label: "shadcn/ui" },
    { id: "Less", label: "Less" },
    { id: "Treehouse", label: "Treehouse" },
    { id: "Flutter", label: "Flutter" },
    { id: "Itch.io", label: "Itch.io" },
    { id: "YouTube", label: "YouTube" },
    { id: "Objective-C", label: "Objective-C" },
    { id: "freeCodeCamp", label: "freeCodeCamp" },
    { id: "Tether", label: "Tether" },
    { id: "Arch Linux", label: "Arch Linux" },
    { id: "Messenger", label: "Messenger" },
    { id: "Alpine.js", label: "Alpine.js" },
    { id: "DaisyUI", label: "DaisyUI" },
    { id: "Oculus", label: "Oculus" },
    { id: "Rider", label: "Rider" },
    { id: "Hugo", label: "Hugo" },
    { id: "WebAssembly", label: "WebAssembly" },
    { id: "HTML", label: "HTML" },
    { id: "Oracle", label: "Oracle" },
    { id: "Scikit-learn", label: "Scikit-learn" },
    { id: "CSS", label: "CSS" },
    { id: "GitLab CI", label: "GitLab CI" },
    { id: "Django", label: "Django" },
    { id: "Mercurial", label: "Mercurial" },
    { id: "Dev.to", label: "Dev.to" },
    { id: "ETL", label: "ETL" },
    { id: "Gmail", label: "Gmail" },
    { id: "Nix", label: "Nix" },
    { id: "Proton Drive", label: "Proton Drive" },
    { id: "Zig", label: "Zig" },
    { id: "Remix", label: "Remix" },
    { id: "FastAPI", label: "FastAPI" },
    { id: "Artix Linux", label: "Artix Linux" },
    { id: "Travis CI", label: "Travis CI" },
    { id: "SAP", label: "SAP" },
    { id: "NodeJS", label: "NodeJS" },
    { id: "styled-components", label: "styled-components" },
    { id: "Opera", label: "Opera" },
    { id: "BeReal", label: "BeReal" },
    { id: "jQuery", label: "jQuery" },
    { id: "Composer", label: "Composer" },
    { id: "Rocky Linux", label: "Rocky Linux" },
    { id: "Gitea", label: "Gitea" },
    { id: "Yarn", label: "Yarn" },
    { id: "LinkedIn Learning", label: "LinkedIn Learning" },
    { id: "Monster", label: "Monster" },
    { id: "Express.js", label: "Express.js" },
    { id: "Windows", label: "Windows" },
    { id: "GitHub", label: "GitHub" },
    { id: "Ghost", label: "Ghost" },
    { id: "Udacity", label: "Udacity" },
    { id: "Playwright", label: "Playwright" },
    { id: "PhpStorm", label: "PhpStorm" },
    { id: "Doordash", label: "Doordash" },
    { id: "W3Schools", label: "W3Schools" },
    { id: "XML", label: "XML" },
    { id: "Emacs", label: "Emacs" },
    { id: "SvelteKit", label: "SvelteKit" },
    { id: "Three.js", label: "Three.js" },
    { id: "DeviantArt", label: "DeviantArt" },
    { id: "Sphinx", label: "Sphinx" },
    { id: "Teradata", label: "Teradata" },
    { id: "Codacy", label: "Codacy" },
    { id: "Buy Me A Coffee", label: "Buy Me A Coffee" },
    { id: "F#", label: "F#" },
    { id: "Quora", label: "Quora" },
    { id: "Vue.js", label: "Vue.js" },
    { id: "Brave", label: "Brave" },
    { id: "JSON", label: "JSON" },
    { id: "MySQL", label: "MySQL" },
    { id: "MongoDB", label: "MongoDB" },
    { id: "Google Drive", label: "Google Drive" },
    { id: "EA", label: "EA" },
    { id: "Google Chrome", label: "Google Chrome" },
    { id: "AssemblyScript", label: "AssemblyScript" },
    { id: "Clojure", label: "Clojure" },
    { id: "Snapchat", label: "Snapchat" },
    { id: "ChatGPT", label: "ChatGPT" },
    { id: "Sass", label: "Sass" },
    { id: "SQLite", label: "SQLite" },
    { id: "Google", label: "Google" },
    { id: "Debian", label: "Debian" },
    { id: "Shopify", label: "Shopify" },
    { id: "WordPress", label: "WordPress" },
    { id: "Google Colab", label: "Google Colab" },
    { id: "Trustpilot", label: "Trustpilot" },
    { id: "PlayStation Store", label: "PlayStation Store" },
    { id: "Tumblr", label: "Tumblr" },
];
