export const TAGS: string[] = [
    "JavaScript",
    "HTML",
    "CSS",
    "NodeJS",
    "Python",
    "Java",
    "TypeScript",
    "C++",
    "C#",
    "PHP",
    "Go",
    "Ruby",
    "Swift",
    "Kotlin",
    "Rust",
    "C",
    "Scala",
    "Dart",
    "Solidity",
    "Crystal",
    "Elixir",
    "Nim",
    "OCaml",
    "R",
    "Lua",
    "Objective-C",
    "Haskell",
    "V",
    "F#",
    "AssemblyScript",
    "Clojure",
    "Zig",
    "React",
    "Next.js",
    "Angular",
    "Vue.js",
    "Svelte",
    "SvelteKit",
    "jQuery",
    "Bootstrap",
    "TailwindCSS",
    "Redux",
    "Vite",
    "Webpack",
    "Babel",
    "Jest",
    "Spring Boot",
    "Django",
    "Laravel",
    "Rails",
    "Express.js",
    "Flask",
    "React Native",
    "Flutter",
    "Electron",
    "Sass",
    "Less",
    "PostCSS",
    "GraphQL",
    "Apollo",
    "REST",
    "gRPC",
    "WebSockets",
    "PWA",
    "Serverless",
    "Microservices",
    "Fastify",
    "Hono",
    "Three.js",
    "Remix",
    "Astro",
    "Gatsby",
    "React Router",
    "React Hook Form",
    "Vitest",
    "Playwright",
    "Cypress",
    "Mocha",
    "Jasmine",
    "Markdown",
    "MySQL",
    "Postgres",
    "MongoDB",
    "SQLite",
    "Redis",
    "Microsoft SQL Server",
    "Oracle",
    "Firebase",
    "Kubernetes",
    "Neo4J",
    "DynamoDB",
    "Cassandra",
    "CouchDB",
    "Couchbase",
    "MariaDB",
    "ArangoDB",
    "Elasticsearch",
    "Snowflake",
    "InfluxDB",
    "Prisma",
    "TypeORM",
    "Drizzle",
    "AWS",
    "Microsoft Azure",
    "Google Cloud",
    "Docker",
    "Podman",
    "K3s",
    "Jenkins",
    "GitHub Actions",
    "GitLab CI",
    "CircleCI",
    "Travis CI",
    "Terraform",
    "Ansible",
    "Prometheus",
    "Grafana",
    "Supabase",
    "Heroku",
    "Netlify",
    "Vercel",
    "DigitalOcean",
    "Cloudflare",
    "Git",
    "GitHub",
    "GitLab",
    "Bitbucket",
    "npm",
    "pnpm",
    "Yarn",
    "Homebrew",
    "Chocolatey",
    "Scoop",
    "Make",
    "CMake",
    "Meson",
    "IntelliJ IDEA",
    "PyCharm",
    "WebStorm",
    "Visual Studio",
    "VS Code",
    "Sublime Text",
    "Vim",
    "Neovim",
    "Xcode",
    "Eclipse",
    "PhpStorm",
    "Notepad++",
    "Obsidian",
    "Zsh",
    "Bash",
    "Fish Shell",
    "tmux",
    "Alacritty",
    "WezTerm",
    "Kitty",
    "VSCodium",
    "Storybook",
    "shadcn/ui",
    "Figma",
    "Canva",
    "AI",
    "Machine Learning",
    "Data Science",
    "Big Data",
    "Pandas",
    "NumPy",
    "Matplotlib",
    "Scikit-learn",
    "TensorFlow",
    "PyTorch",
    "Hugging Face",
    "Hugging Face Spaces",
    "Anaconda",
    "ETL",
    "DVC",
    "MLflow",
    "Blockchain",
    "Web3",
    "AR",
    "VR",
    "IoT",
    "Cybersecurity",
    "Wireshark",
    "Metasploit",
    "Burp Suite",
    "Nmap",
    "Aircrack-ng",
    "John the Ripper",
    "Hashcat",
    "Hydra",
    "OWASP ZAP",
    "Nikto",
    "sqlmap",
    "Volatility",
    "Autopsy",
    "Maltego",
    "OpenVAS",
    "ClamAV",
    "Suricata",
    "Snort",
    "Shodan",
    "Cuckoo Sandbox",
    "Binwalk",
    "Radare2",
    "Ghidra",
    "IDA Free",
    "YARA",
    "Chkrootkit",
    "Rkhunter",
    "Lynis",
    "Fail2Ban",
    "KeePassXC",
    "Bitwarden",
    "Pass",
    "Cryptr",
    "OpenSSL",
    "WireGuard",
    "OpenVPN",
    "Tor",
    "Tails",
    "Kali Linux",
    "Parrot OS",
    "Security Onion",
    "MITRE ATT&CK",
    "CTF",
    "Hack The Box",
    "TryHackMe",
    "OverTheWire",
    "PicoCTF",
    "Root Me",
    "Linux",
    "Ubuntu",
    "Fedora",
    "Arch Linux",
    "Debian",
    "Alpine Linux",
    "GitHub Copilot",
    "Copilot Chat",
    "Cursor",
    "JSON",
    "XML",
    "OpenCV",
    "NLTK",
    "OpenAI API",
    "LangChain",
    "Godot Engine",
    "Unity",
    "Unreal Engine",
    "GameMaker",
    "Scratch",
    "ROS",
    "MATLAB",
    "Octave",
    "SPSS",
    "LaTeX",
    "Overleaf",
    "Hadoop",
    "Spark",
    "Tableau",
    "Power BI",
    "Jupyter Notebook",
    "Colab",
    "Kaggle",
    "GNU",
    "FFmpeg",
    "ImageMagick",
    "GIMP",
    "Krita",
    "Inkscape",
    "LibreOffice",
    "Pandoc",
    "MkDocs",
    "Sphinx",
    "Docusaurus",
    "Docsify",
    "Zotero",
    "Logseq",
    "Minikube",
    "Helm",
    "Tilt",
    "K9s",
    "HTTPie",
    "Postman",
    "Insomnia",
    "Vibecoding",
    "Vibecharting",
    "Replit",
    "Glitch",
    "CodeSandbox",
    "StackBlitz",
    "JSFiddle",
    "Gitpod",
    "Dev.to",
    "Hashnode",
    "Medium",
    "LeetCode",
    "HackerRank",
    "Codewars",
    "MongoDB Atlas",
    "MongoDB Compass",
    "Anthropic Claude",
    "Google Gemini",
    "Perplexity AI",
    "MCP",
    "LangSmith",
    "OpenDevin",
    "AutoGPT",
    "BabyAGI",
    "Meta LLaMA",
    "LoRA",
    "Weights & Biases",
    "Paperspace",
    "RunPod",
    "Modal",
    "BentoML",
    "Streamlit",
    "Gradio",
    "FastAPI",
    "Flask-SocketIO",
];
